name: Dedication
main: com.psygate.dedication.Dedication
version: 1.2
author: Nok, psygate
softdepend: [CombatTagPlus, Citadel]

commands:
    timer:
        description: Shows you how much time is left.
        usage: /dtl (<playernames...>)
        aliases: [dtl]
        permission: dedication.timer.show
    bypass:
        description: Sets bypass mode for dedication.
        aliases: [ddb]
        usage: /ddb <playername>
        permission: dedication.admin.setbypass
    flush:
        description: Flushs all cache data to the disk.
        aliases: [df]
        usage: /df
        permission: dedication.admin.flush
    dreload:
        description: Reloads all data from disk. It might be advisable to flush first to avoid loss of data.
        aliases: [dr]
        usage: /dr
        permission: dedication.admin.reload
    mute:
        description: Ignores dedication messages for a set time.
        aliases: [di]
        usage: /di <time in minutes>
        permission: dedication.messages.ignore

permissions:
    dedication.bypass:
        description: Allows the player to bypass dedication.
        default: op
    dedication.admin.setbypass:
        description: Allows setting of bypass mode for dedication.
        default: op
    dedication.timer.show:
        description: Allows showing of the dedication time.
        default: true
    dedication.admin.extensiveinfo:
        description: Allows access to extensive information about dedication.
        default: op
    dedication.admin.flush:
        description: Flushs the cache to disk.
        default: op
    dedication.admin.reload:
        description: Reloads all settings.
        default: op
    dedication.messages.ignore:
        description: Allows players to ignore messages.
        default: true
    dedication.admin:
        description: Allows modification of dedication.
        children:
            dedication.admin.setbypass: true
            dedication.admin.setbypass: true
            dedication.admin.extensiveinfo: true
            dedication.admin.seeothers: true
            dedication.admin.flush: true
            dedication.admin.reload: true